"""empty message

Revision ID: 5f4ea9d9b3ff
Revises: d53283a9036a
Create Date: 2020-07-21 11:08:12.092949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f4ea9d9b3ff'
down_revision = 'd53283a9036a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address1', sa.String(length=150), nullable=False),
    sa.Column('address2', sa.String(length=150), nullable=True),
    sa.Column('address3', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_address',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address1', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('address2', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('address3', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_address_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_addresses')
    # ### end Alembic commands ###
