"""empty message

Revision ID: ae57cf419e3a
Revises: 5f4ea9d9b3ff
Create Date: 2020-07-22 18:34:08.937513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae57cf419e3a'
down_revision = '5f4ea9d9b3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_image', sa.String(length=150), nullable=True),
    sa.Column('in_stock', sa.String(length=10), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'mobile',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mobile',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_table('products_meta')
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
